service: e0-py-lambda-ses-notifier
frameworkVersion: "3"

provider:
  name: aws
  stage: poc
  region: eu-west-1
  deploymentPrefix: lambda-ses-notifier
  memorySize: 256
  timeout: 60
  versionFunctions: false
  tracing:
    lambda: true

custom:
  pythonRequirements:
    layer:
      name: e0-py-lambda-ses-notifier
      description: "Layer which contains the python libraries"
      compatibleRuntimes:
        - python3.11
        - python3.10
      compatibleArchitectures:
        - x86_64

functions:
  # the permission statement is not mandatory in this case because has been configured using terraform project.
  ses-notifier:
    handler: src.notifier.notifier.handler
    runtime: python3.10
    description: This function provides a mechanism to notify the aws users (with password enabled) when their password is expired
    environment:
      POWERTOOLS_SERVICE_NAME: e0-py-lambda-ses-notifier
      LOG_LEVEL: info
    logRetentionInDays: 5
    events:
      - schedule:
          rate: cron(0 10 ? * MON-FRI *)
          enabled: true
          inputTransformer:
            inputPathsMap:
              eventTime: '$.time'
            inputTemplate: '{"time": <eventTime>}'
    layers:
      - Ref: PythonRequirementsLambdaLayer


plugins:
  - serverless-better-credentials
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!dist/**'
    - '!.idea/**'
    - '!src/*.egg-info'
    - '!package-lock.json'
    - '!.package.json'
    - '!node_modules/**'
    - '!serverless-better-credentials/**'
    - 'README.md'
    - 'VERSION'
    - 'src/**'
    - '*.toml'
    - '*.cfg'
    - 'requirements.txt'
  excludeDevDependencies: true



