service: lambda-ses-notifier
frameworkVersion: "3"

provider:
  name: aws
  profile: <your-profile-key>
  region: <your-region-code>
  deploymentPrefix: lambda-ses-notifier
  memorySize: 256
  timeout: 60
  versionFunctions: false
  tracing:
    lambda: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ses:CreateTemplate'
            - 'ses:ListTemplates'
            - 'ses:SendEmail'
            - 'ses:SendRawEmail'
          Resource: [ '*' ]
        - Effect: Allow
          Action:
            - 'iam:GenerateCredentialReport'
            - 'iam:GetCredentialReport'
            - 'iam:ListUserTags'
          Resource: [ '*' ]
        - Effect: 'Allow'
          Action:
            - 'sts:AssumeRole'
          Resource: [ "*" ]

custom:
  pythonRequirements:
    layer:
      description: "Layer which contains the python libraries"
      compatibleRuntimes:
        - python3.11
        - python3.10
      compatibleArchitectures:
        - x86_64

functions:
  ses-notifier:
    handler: src.notifier.notifier.handler
    runtime: python3.11
    description: This function provides a mechanism to notify the aws users (with password enabled) when their password is expired
    environment:
      POWERTOOLS_SERVICE_NAME: lambda-ses-notifier
      LOG_LEVEL: INFO
      POWERTOOLS_LOGGER_LOG_EVENT: True
      POWERTOOLS_LOG_LEVEL: INFO
      EMAIL_FROM: <youremail@yourdomain.com>
      OLD_AGE_PASSWORD: 75
    logRetentionInDays: 5
    events:
      - schedule:
          rate: cron(0 10 ? * MON-FRI *)
          enabled: true
          inputTransformer:
            inputPathsMap:
              eventTime: '$.time'
            inputTemplate: '{"time": <eventTime>}'
    layers:
      - Ref: PythonRequirementsLambdaLayer


plugins:
  - serverless-better-credentials
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!dist/**'
    - '!.idea/**'
    - '!src/*.egg-info'
    - '!package-lock.json'
    - '!.package.json'
    - '!node_modules/**'
    - '!serverless-better-credentials/**'
    - 'README.md'
    - 'VERSION'
    - 'src/**'
    - '*.toml'
    - '*.cfg'
    - 'requirements.txt'
  excludeDevDependencies: true



